version: "3"
services:
  cat-photo-db:
    container_name: cat-photo-db
    image: "mysql:8"
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=cat_photos
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 20s
      retries: 10
  cat-photo-server:
    container_name: cat-photo-server
    image: cat-photo-server
    build: .
    ports:
      - 8080:8080
    depends_on:
      cat-photo-db:
        condition: service_healthy
    volumes:
      - ${PWD}/data:/data
